[workspace]
resolver = "2"
members = [
    "projects/*",
    "examples/*"
]
default-members = [
    "projects/gaia-types",
    "projects/gaia-assembler",
    "projects/gaia-jit",
    "examples/wasi-assembler",
    "examples/clr-assembler",
    "examples/elf-assembler",
    "examples/gcn-assembler",
    "examples/jvm-assembler",
    "examples/lua-assembler",
    "examples/llvm-assembler",
    "examples/pe-assembler",
    "examples/x86_64-assembler",
    "examples/macho-assembler",
    "examples/msl-assembler",
    "examples/sass-assembler",
    "examples/spirv-assembler",
    "examples/pyc-assembler"
]
exclude = [
    "projects/.DS_Store",
    "projects/gaia-document",
]

[workspace.package]
version = "0.0.5"
edition = "2024"
authors = ["Gaia Team <192607617↯qq.com>"]
license = "MPL-2.0"
repository = "https://github.com/nyar-vm/project-gaia"
homepage = "https://gaia-assembly.netlify.app/"

[workspace.dependencies]
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.149"
byteorder = "1.5.0"
url = { version = "2.5.8", features = ["serde"] }
tracing = "0.1.44"
walkdir = "2.5.0"
toml = "1.0"
num = "0.4.3"
ordered-float = "5.1.0"
source-map = "0.15.0"
tempfile = "3.25"
bitflags = "2.10"
pretty_assertions = "1.4"
leb128 = "0.2.5"
wat = "1.245.0"
wasmparser = "0.245.0"
wasmtime = "41.0.3"
wasmtime-wasi = "41.0.3"
region = "3.0.2"
windows-sys = { version = "0.61.2", features = ["Win32_System_Memory", "Win32_Foundation", "Win32_System_SystemInformation", "Win32_System_Diagnostics_Debug", "Win32_System_Threading"] }
libc = "0.2"

# External projects for Local
oak-core = { path = "../oaks/projects/oak-core" }
oak-pretty-print = { path = "../oaks/projects/oak-pretty-print" }
oak-msil = { path = "../oaks/examples/oak-msil" }
oak-lua = { path = "../oaks/examples/oak-lua" }
oak-wat = { path = "../oaks/examples/oak-wat" }
oak-jasm = { path = "../oaks/examples/oak-jasm" }
oak-llvm-ir = { path = "../oaks/examples/oak-llvm-ir" }

# External projects for CI
# oak-core = "0.0.3"
# oak-pretty-print = "0.0.3"
# oak-msil = "0.0.3"
# oak-lua = "0.0.3"
# oak-wat = "0.0.3"
# oak-jasm = "0.0.3"
# oak-llvm-ir = "0.0.3"

# Internal projects
gaia-jit = { path = "projects/gaia-jit" }
gaia-types = { path = "projects/gaia-types" }
gaia-assembler = { path = "projects/gaia-assembler" }
x86_64-assembler = { path = "examples/x86_64-assembler" }
gcn-assembler = { path = "examples/gcn-assembler" }
msl-assembler = { path = "examples/msl-assembler" }
sass-assembler = { path = "examples/sass-assembler" }
spirv-assembler = { path = "examples/spirv-assembler" }
pe-assembler = { path = "examples/pe-assembler" }
clr-assembler = { path = "examples/clr-assembler" }
jvm-assembler = { path = "examples/jvm-assembler", package = "jasm-assembler" }
elf-assembler = { path = "examples/elf-assembler" }
macho-assembler = { path = "examples/macho-assembler" }
lua-assembler = { path = "examples/lua-assembler" }
llvm-assembler = { path = "examples/llvm-assembler" }
wasi-assembler = { path = "examples/wasi-assembler" }
python-assembler = { path = "examples/pyc-assembler" }


[profile.release]
lto = true
panic = "abort"
