[workspace]
resolver = "2"
members = ["projects/*", "examples/mini-rust"]
default-members = [
    "projects/gaia-types",
    "projects/jvm-jasm",
    "projects/clr-msil",
]
exclude = [
    "projects/.DS_Store",
    "projects/gaia-document",
    "projects/gaia-frontend-wasm32",
]

[workspace.dependencies]

[profile.release]
lto = true
panic = "abort"
