[package]
name = "lua-assembler"
version = { workspace = true }
edition = { workspace = true }
authors = { workspace = true }
license = { workspace = true }
description = "Parse and write Lua .luac bytecode"
homepage = "https://gaia-assembly.netlify.app/backends/lua/"
repository = "https://github.com/nyar-vm/project-gaia/tree/main/examples/lua-assembler"
documentation = "https://docs.rs/lua-assembler"
readme = "readme.md"
exclude = ["package.json"]

[dependencies]
byteorder = { workspace = true }
gaia-types = { workspace = true }
serde = { workspace = true }
oak-core = { workspace = true }
oak-pretty-print = { workspace = true }
oak-lua = { workspace = true, features = ["oak-pretty-print"] }

[build-dependencies]

[dev-dependencies]
gaia-types = { workspace = true, features = ["serde_json"] }
serde_json = { workspace = true }
walkdir = { workspace = true }
tempfile = { workspace = true }

[features]
default = []
easy-test = []

[package.metadata.docs.rs]
all-features = true
