[package]
name = "macho-assembler"
version = { workspace = true }
edition = { workspace = true }
authors = { workspace = true }
license = { workspace = true }
description = "Mach-O assembler for Gaia project"
homepage = "https://gaia-assembly.netlify.app/backends/macho/"
repository = "https://github.com/nyar-vm/project-gaia/tree/main/examples/macho-assembler"
documentation = "https://docs.rs/macho-assembler"
readme = "readme.md"
exclude = ["package.json"]

[dependencies]
byteorder = { workspace = true }
gaia-types = { workspace = true }
serde = { workspace = true }
tracing = { workspace = true }
x86_64-assembler = { workspace = true }

[features]
default = []

[package.metadata.docs.rs]
all-features = true
