[package]
name = "gaia-types"
version = { workspace = true }
edition = { workspace = true }
authors = { workspace = true }
license = { workspace = true }
description = "Type system for Gaia project"
homepage = "https://gaia-assembly.netlify.app/types/"
repository = "https://github.com/nyar-vm/project-gaia/tree/main/projects/gaia-types"
documentation = "https://docs.rs/gaia-types"
readme = "readme.md"
exclude = ["package.json"]

[dependencies]
url = { workspace = true, features = ["serde"] }
source-map = { workspace = true }
byteorder = { workspace = true }
tracing = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true, optional = true }

[dev-dependencies]

[features]
default = []

[package.metadata.docs.rs]
all-features = true
