[package]
name = "gaia-assembler"
version = { workspace = true }
edition = { workspace = true }
authors = { workspace = true }
license = { workspace = true }
description = "Universal assembler framework for Gaia project"
homepage = "https://gaia-assembly.netlify.app/assembler/"
repository = "https://github.com/nyar-vm/project-gaia/tree/main/projects/gaia-assembler"
documentation = "https://docs.rs/gaia-assembler"
readme = "readme.md"
exclude = ["package.json"]

[dependencies]
wasi-assembler = { workspace = true }
gaia-types = { workspace = true }
serde = { workspace = true }
toml = { workspace = true }
num = { workspace = true }
byteorder = { workspace = true }
ordered-float = { workspace = true }
oak-core = { workspace = true }
jvm-assembler = { workspace = true }
pe-assembler = { workspace = true }
gcn-assembler = { workspace = true }
sass-assembler = { workspace = true }
clr-assembler = { workspace = true, optional = true }

[dev-dependencies]

[features]
default = []
easy-test = []
clr = ["clr-assembler"]

[package.metadata.docs.rs]
all-features = true
